apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: ops
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "7.*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: ops
      interval: 1h

  values:
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: local-path   # keep simple for now

    adminUser: admin
    adminPassword: admin123   # weâ€™ll improve this later

    service:
      type: ClusterIP

    ingress:
      enabled: false   # we'll handle ingress separately

