apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ops
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/ops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra
  wait: true
  timeout: 10m

