apiVersion: v1
kind: Service
metadata:
  name: vmagent
  namespace: ops
  labels:
    app.kubernetes.io/name: vmagent
spec:
  selector:
    app.kubernetes.io/name: victoria-metrics-agent
    app.kubernetes.io/instance: vmagent
  ports:
    - name: http
      port: 8429
      targetPort: 8429
