apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media
spec:
  capacity:
    storage: 10Ti  # label only; NFS doesn't enforce quotas
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # empty = static PV (not provisioned)
  nfs:
    server: 192.168.0.13
    path: /export/media
